# Generated by Django 3.2.9 on 2021-12-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('year', models.IntegerField(choices=[(2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010)])),
                ('color', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
