# Generated by Django 3.2.9 on 2021-12-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20211215_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='cars',
            name='brand',
        ),
        migrations.AlterField(
            model_name='cars',
            name='model',
            field=models.CharField(max_length=25),
        ),
        migrations.AddField(
            model_name='cars',
            name='brand',
            field=models.ManyToManyField(related_name='Car', to='cars.Brands'),
        ),
    ]
