# Generated by Django 3.2.9 on 2021-12-20 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20211220_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='brand',
            field=models.CharField(max_length=30),
        ),
        migrations.RemoveField(
            model_name='cars',
            name='brand',
        ),
        migrations.AddField(
            model_name='cars',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='cars.brands'),
            preserve_default=False,
        ),
    ]
