# Generated by Django 3.2.9 on 2021-12-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20211220_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='cars',
            name='opt',
            field=models.ManyToManyField(to='cars.Opt'),
        ),
    ]
