# Generated by Django 3.2.9 on 2021-12-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20211220_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='opt',
            field=models.ManyToManyField(related_name='opt_cars', to='cars.Opt'),
        ),
    ]
